# This is a basic workflow to help you get started with Actions

name: OnlineWebPublish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the source branch
on:
  push:
    branches:
      - web
      - source 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 1-2.Check and Clone Dest Repo
        env:
          GH_REF: github.com/lucy2003/lucy2003.github.io.git # GitHub 仓库 SSH 地址
          GH_TOKEN: ${{ secrets.Access_Token }}
        run: |
          git config --global user.name "Lucy2003"
          git config --global user.email "2551280097@qq.com"
          git clone -b master https://${GH_REF} ../public-dir
          rm -rf ./.git
          cp -rf ./* ../public-dir
          cd ../public-dir
          git add -A
          git commit -m "Online Update at `date +"%Y-%m-%d %H:%M:%S"`"
          git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
          
          
