# This is a basic workflow to help you get started with Actions

name: OnlineDownloadsPub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the source branch
on:
  workflow_dispatch:
  push:
    paths: 
      - 'downloads/**'
      - '.github/**'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: 1.Clone Public
        env:
          GH_REF: github.com/lucy2003/lucy2003.github.io.git # GitHub 仓库 SSH 地址
          GH_TOKEN: ${{ secrets.Access_Token }}
        run: |
          git config --global user.name "Lucy2003"
          git config --global user.email "2551280097@qq.com"
          git clone -b master https://${GH_REF} ../public-dir
          rm -rf ./.git
      - name: 2. Compile program and process dir
        run: |
          gcc ./.github/main.c -O2 -o ./MakeFileList
          ./MakeFileList ./downloads
      - name: 3.Publish
        run: |
          rm -rf ../public-dir/downloads
          cp -rf ./downloads ../public-dir
          cd ../public-dir
          rm -rf ./.github
          git add -A
          git commit -m "Online Update at `date +"%Y-%m-%d %H:%M:%S"`"
          git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
